import GameList from "@/components/pages/customer/gameList";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function page() {
	return <GameList />;
}
